name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install global dependencies
      run: |
        sudo apt update
        sudo apt install openjdk-8-jdk
    - name: Install dependencies
      run: npm install
    - name: Build and Test services
      run: npm run buildonly