name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global dependencies
        run: |
          sudo apt update
          sudo apt install openjdk-8-jdk
      - name: Install dependencies
        run: npm install
      - name: Run Format Checker
        run: npm run check:format
        working-directory: ./
        timeout-minutes: 10
      - name: Install globally required packages
        run: |
          npm i -g bestzip
          npm i -g copyfiles
      - name: Build, Test services and create Bundle
        run: |
          npm run buildbundle
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            services.zip
            eformservice-*.tgz
          prerelease: ${{ contains(github.ref, '-') }} # If tag contains -, it's a prerelease (e.g. /refs/tags/v8.30.0-0)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}