name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global dependencies
        run: |
          sudo apt update
          sudo apt install openjdk-8-jdk
      - name: Install dependencies
        run: npm install
      - name: Install globally required packages
        run: |
          npm i -g bestzip
          npm i -g copyfiles
      - name: Build, Test services and create Bundle
        run: |
          npm run buildbundle
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            services.zip
            eformservice-*.tgz
          prerelease: ${{ true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}