name: Trigger Release Creation

on:
  workflow_dispatch:
    inputs:
      prassignee:
        description: "User to assign PR to (defaults to current user)"
        required: false
        type: string
      sdkversion:
        description: 'SDK Version (e.g. "v9.8.0")'
        required: true
        default: "v"
      isfinalreleasebuild:
        description: "Build final release build? (if unchecked, this builds a pre-release)"
        required: true
        type: boolean
        default: false

env:
  NODE_VERSION: 22

jobs:
  configure:
    name: Configure Release Branch
    runs-on: ubuntu-latest
    env:
      isprereleasebuild: ${{ inputs.isfinalreleasebuild != true }}
      prassignee: ${{ inputs.prassignee || github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.DEVBOT_GH_TOKEN }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Configure Git
        run: |
          git config user.name 'Development Bot'
          git config user.email 'devbot@roxtra.com'
      - name: Install dependencies
        run: npm ci
      - name: Update SDK
        # Replace processHubSDKVersion in buildScript.js with new version
        # Build all services to update package-lock.json files
        # Commit changes if there are changes. This works the following way:
        # First, add all unstaged changes in the working tree if there are changes
        # Second: if the git diff command has an exit code other than 0 (=there are changes), make the commit. Otherwise, do not commit.
        run: |
          sed -i -r 's/processHubSDKVersion = "v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?"/processHubSDKVersion = "${{ github.event.inputs.sdkversion }}"/g' buildScript.js
          npm run buildonly
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update SDK"
      - id: version-upgrade
        name: Upgrade Version
        # Make next RC Final or, if sdkversion is a prerelease (contains a "-"), create a prerelease
        run: |
          if ${{ env.isprereleasebuild }}; then npm version prerelease; else npm version minor; fi
          NEWVERSION=$(echo "console.log(require('./package.json').version);" | node)
          echo "newversion=$(echo $NEWVERSION)" >> $GITHUB_OUTPUT
      - name: Create Branch and Push Branch and Tag
        run: |
          echo "Create Release Branch"
          git checkout -b release-v${{ steps.version-upgrade.outputs.newversion }}
      - name: Bump Version to next RC
        # Only bump version to next RC if release is non-prerelease
        if: ${{ env.isprereleasebuild == 'false' }}
        run: |
          echo "Bump Version to next RC"
          npm version --git-tag-version false preminor
          git commit -a -m "Bump RC Version"
      - name: Push Branch and Tag
        run: |
          echo "Push branch and tag"
          git push -u origin release-v${{ steps.version-upgrade.outputs.newversion }}
          git push origin v${{ steps.version-upgrade.outputs.newversion }}
      - name: Create PR for new Version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base master --head release-v${{ steps.version-upgrade.outputs.newversion }} --title "Release v${{ steps.version-upgrade.outputs.newversion }}" --body "Updates version to v${{ steps.version-upgrade.outputs.newversion }}" --assignee "${{ env.prassignee }}"
